name: PR Check Merge

on:
  pull_request_target:
    types: [opened]

permissions:
  contents: read

jobs:
  pr-check-merge:
    permissions:
      issues: write  
      pull-requests: write 
    runs-on: ubuntu-latest
    if: (github.event.pull_request.head.ref == 'feature' || github.event.pull_request.head.ref == 'main') 
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          issue-number: ${{ github.event.number }}
          body: |
            Hi